name = "Barry Server Pack"
author = "Daniel and Barry"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34ab4fb516f1140c8351d6989e3aa45a34488c1ca495e839a0e9f8a10e6e8d85"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
