name = "Barry Server Pack"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "259b083b558480173004a4aee9e00b2e9909359a74c66085d1ef74b0b0e336cb"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
