name = "Barry Server Pack"
author = "Daniel and Barry"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fcb858c56b8bc2c1b72f3c831717dba5c820ec5dcc639a8550d4812bbcc98b1"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
