name = "Barry Server Pack"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e28c0dcb2ec8de4e359fd8c99bce84a00d98f0fcfbaf9386e6fe86af95c184ad"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
