name = "Barry Server Pack"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a90044490b0c6385e896eeba2c1fdc9658ac34f8d2e36727b32734d18e29c0db"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
