name = "Barry Server Pack"
author = "Daniel and Barry"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8da19cd7d46311127d2a80e2b4e01f27b37bbd4f4df4a1c2eec50657ca971ec"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
