name = "Barry Server Pack"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a0bbe3ef0960a4fdb6f57333f2cdae90f0751d79665243f2e7c210eb76bcb90"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
