name = "Barry Server Pack"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88dfc90986991d6078fb0cc67d4c3af9feaf5ed7a8c631b499f91d3cbf737401"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
