name = "Barry Server Pack"
author = "Daniel and Barry"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda0d5e43b5be965747e49410d2b0db424b9505eff86e37230fda21eb1a85668"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
