name = "Barry Server Pack"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb264f72941650d4b061bd9d6f745e655e7b440c7e3e4bfe52ee475730fba2fe"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
