name = "Barry Server Pack"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3835878770c6cc8241711ffa40aadc265b1df335fee64cd645e9fd4c43f27e96"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
