name = "Barry Server Pack"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b874c2749f6cd785a0750094afa29d26f0142b0b867e59becaee7dd829a7640b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
