name = "Barry Server Pack"
author = "Daniel and Barry"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a982c3f04830e7c216e88f1aaf21b212c877359f457bb8152f88ebaca2ff02ca"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
