name = "Barry Server Pack"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d0840a7bd0364bd05cdbc2b7a2a64e6a9dcf10fb6d064374be43e0cfcf05e2b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
